package pojos;
// Generated Dec 31, 2017 4:27:30 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.List;

/**
 * Comments generated by hbm2java
 */
public class Comments implements java.io.Serializable {

    private Integer id;
    private int userId;
    private String message;
    private Date postDate;

    private pojos.Users users;
    private int postId;
    
    private List<pojos.Users> likes;

    public List<Users> getLikes() {
        return likes;
    }

    public void setLikes(List<Users> likes) {
        this.likes = likes;
    }
    

    public Comments() {
    }

    public Comments(int userId, String message, int postId, Date postDate) {
        this.userId = userId;
        this.message = message;
        this.postId = postId;
        this.postDate = postDate;
    }

    public int getPostId() {
        return postId;
    }

    public void setPostId(int postId) {
        this.postId = postId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Date getPostDate() {
        return this.postDate;
    }

    public void setPostDate(Date postDate) {
        this.postDate = postDate;
    }

    public Users getUsers() {
        return users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }
    
    

    @Override
    public String toString() {
        return "Comments{" + "id=" + id + ", userId=" + userId + ", message=" + message + ", postDate=" + postDate + ", postId=" + postId + '}';
    }

}
