package pojos;
// Generated Dec 25, 2017 1:10:23 PM by Hibernate Tools 4.3.1



/**
 * Friends generated by hbm2java
 */
public class Friends  implements java.io.Serializable {


     private Integer id;
     private int userId;
     private int friendId;
     private pojos.Users friendData;

    public Users getFriendData() {
        return friendData;
    }

    public void setFriendData(Users friendData) {
        this.friendData = friendData;
    }

    @Override
    public String toString() {
        return "Friends{" + "id=" + id + ", userId=" + userId + ", friendId=" + friendId + ", friendData=" + friendData + '}';
    }
     
    public Friends() {
    }

    public Friends(int userId, int friendId) {
       this.userId = userId;
       this.friendId = friendId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getFriendId() {
        return this.friendId;
    }
    
    public void setFriendId(int friendId) {
        this.friendId = friendId;
    }




}


