package pojos;
// Generated Dec 25, 2017 1:10:23 PM by Hibernate Tools 4.3.1



/**
 * Friendrequests generated by hbm2java
 */
public class Friendrequests  implements java.io.Serializable {


     private Integer id;
     private int userId;
     private int friendId;

    public Friendrequests() {
    }

    public Friendrequests(int userId, int friendId) {
       this.userId = userId;
       this.friendId = friendId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getFriendId() {
        return this.friendId;
    }
    
    public void setFriendId(int friendId) {
        this.friendId = friendId;
    }




}


