package pojos;
// Generated Jan 3, 2018 12:33:19 AM by Hibernate Tools 4.3.1

/**
 * Groups generated by hbm2java
 */
public class Groups implements java.io.Serializable {

    private Integer id;
    private int createrId;
    private String groupName;
    private Users createrUser;

    public Groups() {
    }

    public Groups(int createrId, String groupName) {
        this.createrId = createrId;
        this.groupName = groupName;
    }

    public Integer getId() {
        return this.id;
    }

    public String getGroupString() {
        return groupName + " By: " + createrUser.getFirstName();
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public int getCreaterId() {
        return this.createrId;
    }

    public void setCreaterId(int createrId) {
        this.createrId = createrId;
    }

    public String getGroupName() {
        return this.groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public Users getCreaterUser() {
        return createrUser;
    }

    public void setCreaterUser(Users createrUser) {
        this.createrUser = createrUser;
    }

    @Override
    public String toString() {
        return "Groups{" + "id=" + id + ", createrId=" + createrId + ", groupName=" + groupName + ", createrUser=" + createrUser + '}';
    }

}
