package pojos;
// Generated Dec 30, 2017 1:15:18 PM by Hibernate Tools 4.3.1



/**
 * Likes generated by hbm2java
 */
public class Likes  implements java.io.Serializable {


     private Integer id;
     private int userId;
     private int fetchId;
     private int postType;

    public Likes() {
    }

    public Likes(int userId, int fetchId, int postType) {
       this.userId = userId;
       this.fetchId = fetchId;
       this.postType = postType;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getFetchId() {
        return this.fetchId;
    }
    
    public void setFetchId(int fetchId) {
        this.fetchId = fetchId;
    }
    public int getPostType() {
        return this.postType;
    }
    
    public void setPostType(int postType) {
        this.postType = postType;
    }

    @Override
    public String toString() {
        return "Likes{" + "id=" + id + ", userId=" + userId + ", fetchId=" + fetchId + ", postType=" + postType + '}';
    }




}


