package pojos;
// Generated Jan 3, 2018 12:33:19 AM by Hibernate Tools 4.3.1



/**
 * Messages generated by hbm2java
 */
public class Messages  implements java.io.Serializable {


     private Integer id;
     private int fromId;
     private int toId;
     private String message;
     private Users fromUser;

    public Users getFromUser() {
        return fromUser;
    }

    public void setFromUser(Users fromUser) {
        this.fromUser = fromUser;
    }

    public Messages() {
    }

    public Messages(int fromId, int toId, String message) {
       this.fromId = fromId;
       this.toId = toId;
       this.message = message;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getFromId() {
        return this.fromId;
    }
    
    public void setFromId(int fromId) {
        this.fromId = fromId;
    }
    public int getToId() {
        return this.toId;
    }
    
    public void setToId(int toId) {
        this.toId = toId;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    @Override
    public String toString() {
        return "Messages{" + "id=" + id + ", fromId=" + fromId + ", toId=" + toId + ", message=" + message + ", fromUser=" + fromUser + '}';
    }
    




}


