package pojos;
// Generated Dec 25, 2017 10:19:55 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Posts generated by hbm2java
 */
public class Posts  implements java.io.Serializable {


     private Integer id;
     private int userId;
     private String body;
     private Date postDate;

    public Posts() {
    }

    public Posts(int userId, String body, Date postDate) {
       this.userId = userId;
       this.body = body;
       this.postDate = postDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }
    public Date getPostDate() {
        return this.postDate;
    }
    
    public void setPostDate(Date postDate) {
        this.postDate = postDate;
    }




}


