package pojos;
// Generated Dec 25, 2017 12:32:00 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;
     private String username;
     private String password;
     private String email;
     private Date dateOfBirth;
     private Date lastOnline;

    public Users() {
    }

    public Users(String firstName, String lastName, String username, String password, String email, Date dateOfBirth, Date lastOnline) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.username = username;
       this.password = password;
       this.email = email;
       this.dateOfBirth = dateOfBirth;
       this.lastOnline = lastOnline;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public Date getLastOnline() {
        return this.lastOnline;
    }
    
    public void setLastOnline(Date lastOnline) {
        this.lastOnline = lastOnline;
    }
    
    public String getFullName() {
        return firstName+" "+lastName;
    }

    @Override
    public String toString() {
        return "Users{" + "id=" + id + ", firstName=" + firstName + ", lastName=" + lastName + ", username=" + username + ", password=" + password + ", email=" + email + ", dateOfBirth=" + dateOfBirth + ", lastOnline=" + lastOnline + '}';
    }




}


